name: epale_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^2.6.1
  formz: ^0.8.0
  go_router: ^15.1.3
  image_picker: ^1.1.2
  supabase_flutter: ^2.9.0
  timeago: ^3.7.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  riverpod_lint: ^2.6.5

flutter:
  uses-material-design: true
  assets:
    - .env
